INSERT INTO animedb.genre_title (id, name_genre) VALUES (1, 'Action');
INSERT INTO animedb.genre_title (id, name_genre) VALUES (2, 'Fantasy');
INSERT INTO animedb.genre_title (id, name_genre) VALUES (3, 'Romance');
INSERT INTO animedb.genre_title (id, name_genre) VALUES (4, 'Horror');
INSERT INTO animedb.genre_title (id, name_genre) VALUES (7, 'Psychology');
INSERT INTO animedb.genre_title (id, name_genre) VALUES (8, 'Comedy');
INSERT INTO animedb.genre_title (id, name_genre) VALUES (9, 'Detective');
INSERT INTO animedb.genre_title (id, name_genre) VALUES (10, 'Daily life');
INSERT INTO animedb.genre_title (id, name_genre) VALUES (11, 'War');
INSERT INTO animedb.genre_title (id, name_genre) VALUES (12, 'Space');
INSERT INTO animedb.genre_title (id, name_genre) VALUES (13, 'Thriller');
INSERT INTO animedb.genre_title (id, name_genre) VALUES (14, 'Drama');
INSERT INTO animedb.genre_title (id, name_genre) VALUES (15, 'Adventure');
INSERT INTO animedb.genre_title (id, name_genre) VALUES (16, 'Game');