INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (13, 'Кэн', 'Канэки', 'Одноглазый король');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (14, 'Тока', 'Киришима', 'Кролик');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (15, 'Асуна', 'Юки', 'Молния');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (16, 'Кадзуто', 'Киригая', 'Чёрный мечник');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (17, 'Зеро', 'Ту', 'Йота');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (18, 'Хи', 'ро', '016');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (19, 'Алиса', 'Цуберг', 'Алиса синтез 30');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (20, 'Юджио', 'Юджио', 'Юджио');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (21, 'Лелуш', 'Ламперуж', 'Лулу');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (22, 'C.', 'C.', 'Серая ведьма');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (23, 'Нанналли', 'Ламперуж', 'Нанналли ви Британия');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (24, 'Девятый', 'Девятый', 'Сфинкс');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (25, 'Двенадцатый', 'Двенадцатый', 'Сфинкс');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (26, 'Лиза', 'Мисима', 'Риса');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (27, 'Рил', 'Мэйер', 'Рил');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (28, 'Наруто', 'Удзумаки', 'Девятихвостый');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (29, 'Какаши', 'Хатакэ', 'Копирующий ниндзя');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (30, 'Сакура', 'Харуно', 'Лоб');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (31, 'Саскэ', 'Учиха', 'Саскэ');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (32, 'Минато', 'Намикадзэ', 'Жёлтая молния Конохи');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (33, 'Боруто', 'Удзумаки', 'Болт');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (34, 'Тацуя', 'Шиба', 'Бог разрушения');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (35, 'Миюки', 'Шиба', 'Снежная королева');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (36, 'Анджелина', 'Кудо Шилдс', 'Лина');
INSERT INTO animedb.the_character (id, first_name_char, second_name_char, alias) VALUES (37, 'Надя', 'Русланова', 'Надя');